
services:
  vue-ui-tmp:
    container_name: vue-ui-tmp
    build:
        context: .
        args:
          VUE_APP_SERVER_IP : 10.0.0.103
          VUE_APP_SERVER_PORT : 8081
          VUE_APP_SERVER_PATH : http
          VUE_APP_PUBLIC_PATH : ws 

    ports: 
      - "3000:3000"
      - "8081:8080"
    command: ["tail", "-f", "/dev/null"]
    


