
services:
  vue-ui-tmp:
    container_name: vue-ui-tmp
    build:
        context: .
        args:
          VUE_APP_SERVER_IP : http://10.0.0.103
          VUE_APP_SERVER_PORT : :8080
          VUE_APP_SERVER_PATH : /fitness/
          VUE_APP_PUBLIC_PATH : /fitness/ 

    ports: 
      - "3000:80"
      - "8081:8080"
    


